"""empty message

Revision ID: 3501f9e3f765
Revises: 
Create Date: 2024-11-01 22:03:02.429811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3501f9e3f765'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_recipe_category_category', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_recipe_category_id_category'), 'category', ['category_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_recipe_category_id_category'), type_='foreignkey')
        batch_op.create_foreign_key('fk_recipe_category_category', 'category', ['category'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('category_id')

    # ### end Alembic commands ###
